[project]
name = "week04-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"python-dotenv",
	"fastapi",
	"uvicorn[standard]",
	"langchain>=0.2.0",
	"langgraph>=0.0.46",
	"langchain-community>=0.2.0",
	"pydantic-settings",
	"httpx",
	"pytest",
	"pytest-asyncio",
	"anyio",
	"dashscope>=1.19.3",
	"gradio>=4.44.0",
]
